/*
 * 幻灯片内容文件
 * ------------------------------------------------------------------
 * 修改文字：编辑下方 S('章节', '标题', `正文`, { 选项 })。
 * 常用正文组件：cards([...])、list([...])、flow([...])、chip([...])。
 * type:'cover' 生成章节封面；visual:VISUALS.xxx 添加 visuals.js 中的图。
 * 本文件不包含导航逻辑和视觉样式。
 */
const S = (section, title, content, options = {}) => ({ section, title, content, ...options });
const cards = (items, cols = 3) => `<div class="grid-${cols}">${items.map((x,i)=>`<div class="card"><span class="num">${String(i+1).padStart(2,'0')}</span><h3>${x[0]}</h3><p>${x[1]}</p></div>`).join('')}</div>`;
const flow = (items, vertical = false) => `<div class="flow${vertical?' vertical':''}">${items.map(x=>`<div class="flow-item">${x}</div>`).join('')}</div>`;
const list = items => `<ul class="clean">${items.map(x=>`<li>${x}</li>`).join('')}</ul>`;
const chip = items => `<div class="chips">${items.map(x=>`<span class="chip">${x}</span>`).join('')}</div>`;
const evidence = (label, text) => `<div class="evidence"><span>${label}</span><p>${text}</p></div>`;
const quotation = (text, note) => `<blockquote class="quote"><span class="quote-mark">“</span><p>${text}</p><footer>${note}</footer></blockquote>`;

const slides = [
  // 01–06 开场
  S('开场', '把 AI 变成<br><span class="accent">工程团队</span>', `<p class="lead">从 Rust 云服务、可穿戴设备、技术书籍到 AI 时代的工程师的未来</p>${chip(['3 个案例','1 套方法','1 个未来问题'])}`, {type:'cover', kicker:'AI NATIVE ENGINEERING · 2026', visual:VISUALS.hero}),
  S('开场', '今天不讲<br>“如何用 AI 写代码”', `<div class="compare"><div class="compare-side negative"><span class="eyebrow">临时性</span><h3>Prompt 技巧合集</h3><p>一次对话、一次生成；效果依赖当时的上下文与运气，同样的错误还会再犯。</p></div><div class="versus">转变</div><div class="compare-side highlight"><span class="eyebrow">可持续性</span><h3>工程系统</h3><p>规则写进仓库，任务有完成标准，失败会自动暴露；修过的问题不必一再重来。</p></div></div>${evidence('判断标准','关掉当前对话后，下一位 Agent 是否仍然知道怎么正确地继续工作？')}`),
  S('开场', '三个不同方向的项目', `<div class="artifact-proof"><div class="artifact software"><span class="artifact-id">01 · 软件</span><div class="terminal-proof"><i>$</i><code>rustack serve</code><b>READY · 0.7s</b><small>18 个服务 · 779 条路由 · 约 8 MB</small></div><footer><b>Rustack</b><span>由测试和兼容套件验证</span></footer></div><div class="artifact hardware"><span class="artifact-id">02 · 软硬件</span><div class="training-proof"><span class="shoe-signal left">左脚</span><i>∿∿∿</i><div class="phone-proof"><b>训练会话</b><span></span><span></span><span></span></div><i>∿∿∿</i><span class="shoe-signal right">右脚</span></div><footer><b>可穿戴设备</b><span>最终要经过仪器、实物和现场</span></footer></div><div class="artifact knowledge"><span class="artifact-id">03 · 知识</span><div class="book-proof"><div><small>07</small><b>从优化<br>到泛化</b><span></span><span></span><span></span></div><div><small>08</small><b>如何判断<br>模型真的学会了</b><span></span><span></span><span></span></div></div><footer><b>400–500 页技术书</b><span>由来源、审稿和读者理解验证</span></footer></div></div>`, {kicker:'PROOF BEFORE METHOD'}),
  S('开场', '这些东西是 AI<br>“生成”出来的吗？', quotation('<em>不是。</em> AI 写出了大量代码和文字；项目之所以成立，是因为背后有一套<strong>能持续运转的工程闭环</strong>。','代码和文字只是产物，能够反复交付的才是系统。'), {kicker:'THE QUESTION'}),
  S('开场', '从助手到系统', `<div class="d3-chart d3-evolution" data-chart="evolution" aria-label="AI 工程能力从代码补全演进到工程系统"></div><p class="chart-caption">变化不只来自模型变强，也来自上下文、分工和反馈逐步完善。</p>`, {kicker:'EVOLUTION'}),
  S('开场', 'AI 工程产能公式', `<div class="d3-chart d3-factors" data-chart="factors" aria-label="模型、上下文、任务、反馈、验证和人的判断组成串联的交付链路"></div><p class="chart-caption">它们不是六项可选能力，而是一条串联的交付链路。</p>`, {kicker:'THE WEAKEST LINK'}),

  // 07–24 Rustack
  S('话题一 · Rustack', '01<br><span class="accent">构建协议型软件系统</span>', `<p class="lead">localstack 运行缓慢还开始收费，能不能构建一个完全开源免费的，且高性能低消耗的替代品？</p>${chip(['18 SERVICES','779 ROUTES','&lt; 1s BOOT','≈ 8MB'])}`, {type:'cover', kicker:'TOPIC 01 · SOFTWARE', visual:VISUALS.rustack}),
  S('话题一 · Rustack', 'Rustack: 不仅仅是 localstack 的 Rust 版本', `<div class="grid-2"><div>${list(['高性能低带宽低延迟','CI：每个 Job 都能快速拉起独立环境','本地开发：行为确定，不依赖云端账号与网络','集成测试：失败可以稳定复现','交付：单二进制与小镜像降低分发成本'])}</div><div class="card"><span class="eyebrow">PRODUCT THESIS</span><h3>不是“另一个 AWS”</h3><p>而是为 SDK 测试与本地开发优化的协议兼容层。</p>${chip(['单二进制','< 1s 启动','低内存','小镜像'])}</div></div>`, {kicker:'PROBLEM / OPPORTUNITY'}),
  S('话题一 · Rustack', '92 天、146 次提交：Rustack 的研发历程', `<div class="d3-chart d3-rustack-history" data-chart="rustackHistory" aria-label="Rustack 从 S3 纵向切片、兼容性驱动、代码生成到运行时生态的 92 天研发历程"></div>${evidence('加速拐点','前 24 天完成 121 次提交，并从 S3 推进到 17 个服务；外部兼容性测试和配置化代码生成先后进入研发循环。')}`, {kicker:'COMMIT HISTORY · 2026.02.26—05.28'}),
  S('话题一 · Rustack', '项目目标', `<div class="compare"><div class="compare-side"><span class="eyebrow">不做什么</span>${list(['第一天支持全部 AWS 服务','重现 AWS 内部实现','用接口数量代替行为正确性'])}</div><div class="versus">边界</div><div class="compare-side highlight"><span class="eyebrow">做到什么</span>${list(['官方 SDK 无需改业务代码即可连接','同一输入得到可重复的响应与错误','用外部兼容性测试持续量化差距'])}</div></div>${evidence('验收问题','现有 AWS 集成测试，能不能只改服务地址就运行？')}`, {kicker:'SCOPE BEFORE CODE'}),
  S('话题一 · Rustack', '第一个服务：S3', `<div class="architecture"><div class="node"><small>01</small><h3>客户端</h3><p>AWS CLI / SDK</p></div><div class="node"><small>02</small><h3>HTTP 协议</h3><p>路由、签名、XML</p></div><div class="node"><small>03</small><h3>业务逻辑</h3><p>Bucket / Object</p></div><div class="node"><small>04</small><h3>存储与响应</h3><p>内存后端</p></div></div>`, {kicker:'VERTICAL SLICE'}),
  S('话题一 · Rustack', '为什么是 S3？', `${cards([
    ['协议面够宽','REST-XML、SigV4、Streaming、Range、错误响应。'],
    ['状态语义够深','Versioning、Delete Marker、Multipart 生命周期。'],
    ['现成的检验工具多','AWS SDK、MinIO Mint、Ceph 测试都能给出外部证据。']
  ])}${evidence('纵向切片的价值','一次暴露路由、认证、序列化、存储、错误模型与客户端兼容六类问题。')}`),
  S('话题一 · Rustack', '规则越清楚，AI 越能把工作铺开', `<div class="d3-chart d3-model-expansion" data-chart="modelExpansion" aria-label="Smithy 模型通过代码生成器展开为多个 Rust 服务，兼容测试将差距反馈回规格"></div><p class="chart-caption">结构重复、差异明确、参照可靠，Agent 才能安全地展开广度。</p>`, {kicker:'MODEL → GENERATION → VERIFICATION'}),
  S('话题一 · Rustack', '交付可验证的结果', `<div class="timeline"><div class="timeline-item"><b>模型与类型</b><span>模型可以编译</span></div><div class="timeline-item"><b>签名</b><span>通过 SigV4 用例</span></div><div class="timeline-item"><b>协议层</b><span>SDK 请求可解析</span></div><div class="timeline-item"><b>服务逻辑</b><span>增删改查跑通</span></div><div class="timeline-item"><b>自有协议栈</b><span>移除 s3s</span></div><div class="timeline-item"><b>兼容修复</b><span>外部测试回归</span></div></div>${evidence('阶段完成的标准','必须是用户看得见的能力，或机器能判断的结果，不能只是“新增了 20 个文件”。')}`, {kicker:'PHASE ≠ FILE BATCH'}),
  S('话题一 · Rustack', '对话会结束，项目上下文会留下', `<div class="stack"><div class="stack-layer"><b>AGENTS.md</b><span>长期工程规则</span></div><div class="stack-layer"><b>Skills</b><span>可重复的工作方法</span></div><div class="stack-layer"><b>Specs</b><span>当前功能的具体设计</span></div><div class="stack-layer"><b>Tests</b><span>机器可读的事实边界</span></div></div>`, {kicker:'PROJECT CONTEXT'}),
  S('话题一 · Rustack', 'AGENTS.md：<br>项目的操作系统', `<div class="grid-2"><div>${list(['不允许 TODO 与半成品','错误处理与并发模型','类型、安全和资源限制','Rust 工具链与依赖要求'])}</div><div class="code"><span class="c"># Definition of Done</span>\n<span class="f">cargo build</span>\n<span class="f">cargo test</span>\n<span class="f">cargo fmt --check</span>\n<span class="f">cargo clippy -- -D warnings</span></div></div>`, {kicker:'RULES THAT EXECUTE'}),
  S('话题一 · Rustack', 'Spec 不是说明书，而是协作契约', `<table class="mini-table"><thead><tr><th>普通文档</th><th>可执行规格</th></tr></thead><tbody><tr><td>解释系统</td><td>约束系统</td></tr><tr><td>主要给人阅读</td><td>人和 Agent 都能执行</td></tr><tr><td>允许保留模糊</td><td>尽量减少实现时的猜测</td></tr><tr><td>描述功能</td><td>写清边界、错误、测试和完成标准</td></tr></tbody></table>`, {kicker:'CONTRACT'}),
  S('话题一 · Rustack', '一次失败，怎样变成以后不再犯的错', `<div class="failure-case"><div class="failure-input"><span>外部失败</span><b>S3 XML 解析错误</b><code>&lt;Error&gt;InvalidPart&lt;/Error&gt;</code></div><i>→</i><div><span>01</span><b>固定输入</b><small>新增回归测试</small></div><i>→</i><div><span>02</span><b>补清语义</b><small>写进协议规格</small></div><i>→</i><div><span>03</span><b>最小修复</b><small>只改缺失的规则</small></div><i>↺</i><div class="failure-memory"><span>项目记住了</span><b>下一次默认正确</b><small>测试 · 规格 · 实现</small></div></div>`, {kicker:'A FAILURE THAT STAYS FIXED'}),
  S('话题一 · Rustack', '不要让同一个 Agent<br>包办所有角色', `<div class="role-loop"><div class="role-human"><span>人类负责人</span><b>方向 · 取舍 · 责任</b></div><div class="role-track"><div><span>01</span><b>研究</b><small>事实与未知</small></div><i>→</i><div><span>02</span><b>规格</b><small>边界与设计</small></div><i>→</i><div><span>03</span><b>实现</b><small>按依赖展开</small></div><i>→</i><div><span>04</span><b>测试</b><small>把问题变成可复现的失败</small></div><i>→</i><div><span>05</span><b>审查</b><small>独立检查</small></div></div><div class="role-feedback"><span>决策与约束 ↓</span><b>产物、证据与例外 ↑</b></div></div>`, {kicker:'ROLE SEPARATION · FEEDBACK LOOP'}),
  S('话题一 · Rustack', '外部测试，是 AI 最好的老师', `<div class="d3-chart d3-compatibility" data-chart="compatibility" aria-label="Rustack 经过三轮 DynamoDB 兼容性修复，最终通过选定的 457 个 Alternator 用例"></div>${evidence('分母说清楚','这里的 457 / 457 指当时纳入 Rustack 回归的 Alternator 选定用例；数字不代表 DynamoDB 的全部功能。')}`, {kicker:'ALTERNATOR · SELECTED SUITE'}),
  S('话题一 · Rustack', 'AI 不怕测试失败', `${quotation('AI 怕的是没有<strong>高质量、机器可读</strong>的失败信号。','失败测试 → 定位协议语义 → 小范围修改 → 回归验证')}`, {kicker:'THE REAL FEEDBACK LOOP'}),
  S('话题一 · Rustack', 'DEMO', ``, {type:'demo', kicker:'LIVE'}),
  S('话题一 · Rustack', 'Rustack 留下的不只是代码', cards([
    ['规则','把长期要求写进仓库。'],
    ['规格','让设计能够执行和审查。'],
    ['测试','让兼容性问题自己说话。'],
    ['工作方法','让走通过的路可以重走。']
  ],4), {kicker:'TAKEAWAY'}),
  S('话题一 · Rustack', '软件系统，最终由测试说话', `<div class="huge-number">TEST</div><p class="lead">协议测试、兼容性测试、性能基准与独立审查。</p>`, {type:'cover', kicker:'TOPIC 01 · CONCLUSION'}),

  // 25 转场
  S('转场', '从可重复的测试，<br>到不可忽略的现实', `<p class="lead">软件里的失败可以重放；物理世界还会加入温度、遮挡、冲击、噪声和人的动作。</p>${chip(['TEST → MEASURE','CODE → SIGNAL','ASSUMPTION → EXPERIMENT'])}`, {type:'cover', transition:true, kicker:'FROM BITS TO ATOMS', visual:VISUALS.softwareToHardware}),

  // 26–45 Wearable
  S('话题二 · 可穿戴', '02<br><span class="accent">打造软硬件全栈系统</span>', `<p class="lead">从脚下的 IMU、BLE 链路和手机训练会话，到云端的数据处理：每一个判断最终都要回到测量。</p>${chip(['EDGE','BLE','MOBILE','CLOUD','ML'])}`, {type:'cover', kicker:'TOPIC 02 · HARDWARE', visual:VISUALS.wearable}),
  S('话题二 · 可穿戴', '3 天、116 次提交：Kinetic 从鞋端一路长到产品界面', `<div class="d3-chart d3-kinetic-history" data-chart="kineticHistory" aria-label="Kinetic 在 3 天内从 Reflex 鞋端固件、验证闭环、Cortex 接收端扩展到 Thalamus 控制平面和产品界面的 116 次提交"></div>${evidence('加速前提','前 57 次提交先把协议、Flash、BLE 修复和模拟验证做硬；后 59 次才把 Cortex、Thalamus 与 UI 顺着同一份契约展开。')}`, {kicker:'COMMIT HISTORY · 2026.06.19—06.21'}),
  S('话题二 · 可穿戴', '从产品想法开始', `<div class="compare"><div class="compare-side"><span class="eyebrow">VAGUE</span><h3>做一个足球传感器</h3><p>无法估算，也无法验收。</p></div><div class="versus">SPECIFY</div><div class="compare-side highlight"><span class="eyebrow">EXECUTABLE</span><h3>做一个能够支持 3 小时高强度运动的传感器，获取球员的发力方向，发力大小，动作类型，甚至位置等信息</h3><p>明确采样、传输、延迟、并发与完整性。</p></div></div>`),
  S('话题二 · 可穿戴', '先把产品愿望写成工程约束', `<table class="mini-table"><thead><tr><th>用户怎么说</th><th>工程上看什么</th><th>怎样验证</th></tr></thead><tbody><tr><td>训练时感觉不到</td><td>重量、厚度、安装位置</td><td>佩戴与冲击测试</td></tr><tr><td>一场训练不断线</td><td>续航、丢包、缓存深度</td><td>电流曲线与压力测试</td></tr><tr><td>多人同时使用</td><td>连接数、时隙、射频拥塞</td><td>真实场地并发测试</td></tr><tr><td>数据能用于分析</td><td>采样率、同步误差、质量标志</td><td>标注数据与算法评估</td></tr></tbody></table>`, {kicker:'CONSTRAINT SURFACE'}),
  S('话题二 · 可穿戴', '先摸清陌生领域，再谈选型', `${flow(['用户目标','需要测什么','用什么传感器','怎样采样计算','怎样通信','手机端','云端','分析体验'])}<p class="muted" style="margin-top:34px">先弄清楚“还需要知道什么”，再决定“应该买什么”。</p>`, {kicker:'DOMAIN MAPPING'}),
  S('话题二 · 可穿戴', '候选答案 ≠ 工程事实', `<div class="grid-2"><div>${list(['MCU / IMU / GNSS','BLE / LTE-M / NB-IoT','电源 / PCB / 天线','固件 / iOS / 云端 / 机器学习','知道什么可做，什么不可做'])}</div><div class="card"><span class="eyebrow">回到真实世界</span>${chip(['规格书','参考设计','开发板实测','电流分析仪','射频测试','真实运动数据'])}</div></div>`),
  S('话题二 · 可穿戴', '端到端架构', `<div class="architecture"><div class="node"><small>设备端</small><h3>鞋上传感器</h3><p>惯性传感器 · 微控制器 · 存储 · 电池<br>Rust Embassy 固件</p></div><div class="node"><small>手机端</small><h3>接收端</h3><p>Swift 界面 · Rust 核心<br>会话 / 对时 / 重试</p></div><div class="node"><small>云端</small><h3>控制平面</h3><p>认证 · API · S3 · DynamoDB<br>设备注册 / 无线升级</p></div><div class="node"><small>分析</small><h3>数据与模型</h3><p>遥测数据 · 特征处理<br>动作分类</p></div></div>`, {kicker:'SYSTEM VIEW'}),
  S('话题二 · 可穿戴', '五个系统，靠两条反向链路连成一个产品', `<div class="d3-chart d3-kinetic-architecture" data-chart="kineticArchitecture" aria-label="Kinetic 全部 specs 定义的架构：Tendon、Reflex、Cortex、Thalamus 和 Cerebellum 通过数据向前流、控制与证据向后回连成产品，UI 是跨产品契约"></div>${evidence('架构主线','数据从 Tendon 流向 Cerebellum；配置、ACK、质量与模型证据反向回流。UI 只读 Thalamus 授权后的投影，不直连原始数据。')}`, {kicker:'96 SPECS · DATA FORWARD · CONTROL & EVIDENCE BACK', hidden:true}),
  S('话题二 · 可穿戴', '一场训练，如何变成个性化洞察', `<div class="d3-chart d3-product-loop" data-chart="productLoop" aria-label="从球鞋传感器到手机、云端和个性化反馈的数据产品闭环"></div><p class="chart-caption">个人数据只有和自己的长期记录、同类人群放在一起比较，才可能变成有用的训练建议。</p>`, {kicker:'DATA PRODUCT LOOP · BLE → QUIC → INSIGHT'}),
  S('话题二 · 可穿戴', '五个系统可以一起设计/开发', `<div class="d3-chart d3-system" data-chart="system" aria-label="五个系统围绕数据契约协同"></div>${evidence('协同原则','五个系统围绕同一份数据契约并行推进；它们之间是来回反馈，不是做完一个再交给下一个。')}`, {kicker:'CO-DESIGN · CONTRACT AT THE CENTER'}),
  S('话题二 · 可穿戴', '架构决策：<br>两只鞋如何通信？', `<div class="decision-matrix"><div class="dm-head"><span>连接方式</span><span>手机压力</span><span>同步难度</span><span>额外硬件</span><span>适合场景</span></div><div class="dm-row"><b>A</b><strong>双鞋 → 手机</strong><span class="level high">高</span><span class="level mid">中</span><span>无</span><em>个人原型</em></div><div class="dm-row"><b>B</b><strong>副鞋 → 主鞋 → 手机</strong><span class="level low">低</span><span class="level high">高</span><span>无</span><em>连接受限</em></div><div class="dm-row"><b>C</b><strong>双鞋 → 身体中继</strong><span class="level low">低</span><span class="level low">低</span><span>中继器</span><em>稳定训练</em></div><div class="dm-row"><b>D</b><strong>双鞋 → 场边接收器</strong><span class="level low">低</span><span class="level low">低</span><span>接收器</span><em>多人团队</em></div></div><p class="muted" style="margin-top:18px">这张表不给答案，只把原本藏着的取舍摆到台面上，方便讨论和实测。</p>`, {kicker:'ARCHITECTURE DECISION MATRIX'}),
  S('话题二 · 可穿戴', 'AI 可以列选项，不能替你拍板', `${cards([
    ['找全维度','功耗、同步、丢包、遮挡、成本、单点故障。'],
    ['说清假设','把“手机能稳定连两只鞋”写成待验证的判断。'],
    ['安排实验','两种连接方式、同一场地、同一动作，比较实测数据。']
  ])}${evidence('决策记录','保留有哪些选择、为什么这样选、什么证据会推翻它，以及何时需要重做判断。')}`, {kicker:'AI AS DECISION SUPPORT'}),
  S('话题二 · 可穿戴', '买硬件之前，<br>先定义数据契约', `<div class="packet-map"><div class="packet-label">遥测数据包</div><div class="packet-segments"><div class="identity"><span>身份</span><b>设备编号</b><b>会话编号</b></div><div class="ordering"><span>顺序与时间</span><b>序列号</b><b>设备时间</b><b>采样率</b></div><div class="payload"><span>运动数据</span><b>加速度</b><b>角速度</b></div><div class="health"><span>状态</span><b>电量</b><b>固件版本</b><b>质量标志</b></div></div><div class="packet-questions"><span>丢包检测</span><i>·</i><span>双脚对时</span><i>·</i><span>向前兼容</span><i>·</i><span>质量传播</span></div></div>`, {kicker:'DATA CONTRACT · BOUNDARY FIRST'}),
  S('话题二 · 可穿戴', '字段不难，语义才难', `<div class="semantic-timeline"><div class="clock-row"><b>左脚时钟</b><span style="--x:22%">98</span><span style="--x:42%">99</span><span class="missing" style="--x:62%">100 丢失</span><span style="--x:82%">101</span><i></i></div><div class="clock-row drift"><b>右脚时钟</b><span style="--x:22%">98</span><span style="--x:42%">99</span><span style="--x:62%">100</span><span style="--x:82%">101</span><i></i></div><div class="alignment-window"><span>手机对时窗口</span><b>序号找缺口</b><b>时间戳修漂移</b><b>质量标志传到云端</b></div><div class="packet-state"><span>schema v3</span><span>samples × 8</span><span class="warn">gap: 100</span><span>quality: degraded</span></div></div>`, {kicker:'ORDER · CLOCK · VERSION · QUALITY'}),
  S('话题二 · 可穿戴', '硬件没到，也可以先动手', `${flow(['定义格式','模拟传感器数据','Rust 解析核心','iOS 训练会话','云端入口','可视化与模型','换上真实硬件'])}<div class="grid-3" style="margin-top:30px"><div class="card compact"><h3>正常数据</h3><p>稳定频率与双脚同步</p></div><div class="card compact"><h3>故障数据</h3><p>丢包、乱序、时钟漂移</p></div><div class="card compact"><h3>容量数据</h3><p>多人并发与长时间训练</p></div></div>`, {kicker:'DIGITAL TWIN FIRST'}),
  S('话题二 · 可穿戴', '功耗不能只看平均值', `<div class="d3-chart d3-power" data-chart="powerTrace" aria-label="电流随时间变化，BLE 发射和 Flash 写入产生峰值，总能耗由曲线下的面积决定"></div><p class="chart-caption">这是计算原理示意；峰值、重传和真实工况必须由电流分析仪测得。</p>`, {kicker:'CURRENT × TIME = ENERGY'}),
  S('话题二 · 可穿戴', '哪些已经知道，哪些还只是猜测', `<div class="evidence-status"><div class="status-head"><span>工程问题</span><span>当前证据</span><span>下一步</span></div><div class="known"><b>数据格式与端云流程</b><span>模拟数据可以跑通</span><em>压力测试</em></div><div class="simulated"><b>双鞋对时与丢包恢复</b><span>可以注入漂移和缺口</span><em>连接真实设备</em></div><div class="unknown"><b>BLE 距离与人体遮挡</b><span>规格书不能回答</span><em>现地并发实测</em></div><div class="unknown"><b>续航与无线峰值</b><span>只有数据表预算</span><em>电流分析仪</em></div></div>`, {kicker:'KNOWN · SIMULATED · UNMEASURED'}),
  S('话题二 · 可穿戴', '供应链信息不能靠猜', `${quotation('型号、价格、库存、封装和认证状态，都要回到<strong>当下的信息</strong>逐项核实。','物料快照 · 第二来源 · 生命周期 · 认证 · 交期')}`, {kicker:'SUPPLY CHAIN'}),
  S('话题二 · 可穿戴', 'DEMO', ``, {type:'demo', kicker:'LIVE'}),
  S('话题二 · 可穿戴', '到了物理世界，只认测量结果', `<div class="huge-number">MEASURE</div><p class="lead">AI 可以帮你少走弯路，但不能替你测功耗、跑现场、看真实数据。</p>`, {type:'cover', kicker:'TOPIC 02 · CONCLUSION'}),

  // 46 转场
  S('转场', '从测量物理信号，<br>到建立读者信任', `<p class="lead">知识产品同样需要校准：事实靠来源，结构靠概念依赖，表达靠审稿，最终由读者理解来验证。</p>${chip(['SIGNAL → SOURCE','CALIBRATION → REVIEW','DATA → EXPLANATION'])}`, {type:'cover', transition:true, kicker:'FROM ATOMS TO IDEAS', visual:VISUALS.hardwareToKnowledge}),

  // 47–60 Book
  S('话题三 · AI 写书', '03<br><span class="accent">如何构建一本书</span>', `<p class="lead">单独写好一章不难，难的是几十万字始终讲同一件事、使用同一套概念，并且每个事实都有来处。</p>${chip(['PLAN','RESEARCH','DRAFT','REVIEW','BUILD'])}`, {type:'cover', kicker:'TOPIC 03 · KNOWLEDGE', visual:VISUALS.book}),
  S('话题三 · AI 写书', '写一本书，也是一项系统工程', `<div class="engineering-bridge"><div class="bridge-head"><span>软件工程</span><i>解决同类问题</i><span>写书</span></div><div><b>产品需求</b><i>先明确为谁服务</i><strong>读者约定</strong></div><div><b>系统架构</b><i>组织长期结构</i><strong>全书主线</strong></div><div><b>接口契约</b><i>保持边界一致</i><strong>术语与概念约定</strong></div><div><b>依赖关系图</b><i>安排先后关系</i><strong>知识脉络</strong></div><div><b>测试与检查</b><i>阻止错误进入</i><strong>事实与文风审查</strong></div><div><b>构建与发布</b><i>产生最终交付物</i><strong>PDF 与版本发布</strong></div></div>`),
  S('话题三 · AI 写书', '把“记忆”搬进仓库', `<div class="code">books/&lt;book-name&gt;/\n├── <span class="s">AGENTS.md</span>\n├── bukit.yaml\n├── <span class="s">plan/</span>\n├── <span class="s">chapters/</span>\n├── docs/{research,reviews}/\n├── assets/\n├── drafts/\n└── output/</div><p class="muted" style="margin-top:22px">不要让 Agent 记住整本书；让仓库记住最重要的约束。</p>`, {kicker:'REPOSITORY AS MEMORY'}),
  S('话题三 · AI 写书', '先想清楚读者怎样学会，再排目录', `<div class="compare"><div class="compare-side"><span class="eyebrow">知识点目录</span><p>基础 → 原理 → 算法 → 应用</p><p class="muted">容易写成一摞彼此松散的文章。</p></div><div class="versus">转变</div><div class="compare-side highlight"><span class="eyebrow">学习过程</span><p>现在懂什么 → 卡在哪里 → 最后能判断什么</p><p class="muted">让读者沿着一条主线逐步建立能力。</p></div></div>`),
  S('话题三 · AI 写书', '知识不是目录，而是一张依赖图', `<div class="d3-chart d3-knowledge" data-chart="knowledgeGraph" aria-label="数据、表示、模型、损失、优化、泛化、评估、部署和反馈组成带有前置依赖和回访关系的知识图"></div><p class="chart-caption">一章既要说清前置概念，也要为后文留下可以继续使用的判断工具。</p>`, {kicker:'PREREQUISITES · THROUGH-LINES · RETURN'}),
  S('话题三 · AI 写书', '写作约定，像一道类型检查', `<div class="writing-checker"><div class="draft-input"><span>一段初稿</span><p>“模型只要记住训练数据，就可以得到很好的结果。”</p></div><div class="checker-gates"><div><b>读者</b><span>软件工程师能跟上吗？</span></div><div><b>概念</b><span>记忆和泛化被混在一起了吗？</span></div><div class="reject"><b>事实</b><span>结论有来源和边界吗？</span></div><div><b>表达</b><span>是否清楚、克制、可以朗读？</span></div></div><div class="checker-result"><span>返回修改</span><b>禁止模糊的正确</b><small>补机制 · 补证据 · 补失效边界</small></div></div>`, {kicker:'WRITING CONTRACT AS TYPE SYSTEM'}),
  S('话题三 · AI 写书', '一章书，也有自己的流水线', `<div class="chapter-pipeline"><div class="lane-labels"><span>规划</span><span>研究</span><span>写作</span><span>审查</span><span>出版</span></div><div class="pipeline-track"><div><b>全书规划</b><small>主线与读者</small></div><i>›</i><div><b>章节规划</b><small>目标与前后关系</small></div><i>›</i><div><b>资料汇编</b><small>问题与来源</small></div><i class="gate">◆</i><div><b>初稿</b><small>从直觉写到判断</small></div><i>›</i><div><b>三类审查</b><small>技术 · 结构 · 文风</small></div><i class="gate">◆</i><div><b>事实与图表</b><small>证据与解释</small></div><i>›</i><div><b>排版发布</b><small>构建与人工审校</small></div></div><div class="pipeline-gates"><span>第一道门：来源足以支撑写作</span><span>第二道门：审查发现的问题已经解决</span></div></div>`, {kicker:'CHAPTER PRODUCTION PIPELINE'}),
  S('话题三 · AI 写书', '一章内容，应该怎样讲清楚？', `<div class="formula"><span class="accent">直觉</span> → 机制 → 表达 → 边界 → 工程判断</div><div class="grid-3" style="margin-top:34px"><div class="card compact"><h3>动笔之前</h3><p>全书规划、章节规划</p></div><div class="card compact"><h3>写作材料</h3><p>研究资料、相邻章节</p></div><div class="card compact"><h3>写完之后</h3><p>分角色审查与构建</p></div></div>`, {kicker:'WRITING ORDER'}),
  S('话题三 · AI 写书', '四种常见失败', `${cards([
    ['没有主线','每一章单看都不错。'],
    ['文风漂移','越写越像不同作者。'],
    ['读起来合理，事实却不存在','流畅的语言掩盖了事实错误。'],
    ['像课程讲义','定义、列表与模板化结构。']
  ],4)}${evidence('对应护栏','知识脉络 / 写作契约 / 资料汇编 / 独立结构审查。')}`, {kicker:'FAILURE MODES'}),
  S('话题三 · AI 写书', '技术图，不能靠生成式图片', `<div class="compare"><div class="compare-side highlight"><span class="eyebrow">代码 / SVG</span><h3>需要准确的图</h3><p>数据图、坐标图、流程图；保留生成脚本，随时可以重建。</p></div><div class="versus">分工</div><div class="compare-side"><span class="eyebrow">生成式图片</span><h3>负责叙事和氛围</h3><p>适合封面与插画；每一张都要经过人工检查。</p></div></div>`),
  S('话题三 · AI 写书', '排版和发布，也交给流水线', `${flow(['Markdown / DSL','bukit','Typst','PDF','Git 标签','GitHub Actions','发布'])}<div class="chips">${['可重复构建','版本可追踪','可以比较修改','自动发布','多种格式'].map(x=>`<span class="chip">${x}</span>`).join('')}</div>`, {kicker:'PUBLISHING PIPELINE'}),
  S('话题三 · AI 写书', 'AI 写书的真实成本', `<div class="project-record">本项目记录 · 不是行业平均</div><div class="grid-4"><div class="stat"><strong>400–500</strong><span>页 / 本</span></div><div class="stat"><strong>25h+</strong><span>Agent 工作</span></div><div class="stat"><strong>40–50%</strong><span>周额度</span></div><div class="stat"><strong>5–10h</strong><span>人工审校</span></div></div><p class="lead" style="margin-top:38px">AI 没有一键写完一本书，只是把数月的重复劳动压缩进一条更紧凑的流程。</p>`, {kicker:'PROJECT RECORD'}),
  S('话题三 · AI 写书', 'DEMO', ``, {type:'demo', kicker:'LIVE'}),
  S('话题三 · AI 写书', '一本书，最后要过读者这一关', `<div class="huge-number">TRUST</div><p class="lead">事实有没有来源，论证能不能读懂，整本书是否值得信任。</p>`, {type:'cover', kicker:'TOPIC 03 · CONCLUSION'}),

  // 61–66 统一方法论
  S('转场', '项目不同，做成事的方法相通', `<p class="lead">代码、设备和书稿看起来毫不相干；但都要先说清目标和边界，再让执行接受反馈，最后把教训留在项目里。</p>${chip(['目标与边界','执行','验证','项目记忆'])}`, {type:'cover', transition:true, kicker:'THREE WORLDS · ONE LOOP', visual:'<div class="d3-chart d3-convergence" data-chart="convergence" aria-label="软件、软硬件和知识三个工程世界汇入同一套工程闭环"></div>'}),
  S('统一方法论', '失败只有写回系统，才会变成下一次的起点', `<div class="d3-chart d3-memory-loop" data-chart="memoryLoop" aria-label="意图进入执行，软件测试、硬件测量和内容审稿产生外部证据，修正写入规格、测试和规则后回到下一次执行"></div>`, {kicker:'FAILURE → EVIDENCE → MEMORY'}),
  S('统一方法论', '实现更快后，工程师把时间花到哪里', `<div class="attention-shift"><div><span>实现成本高时</span><div class="attention-bar old"><i style="--w:48%">亲手实现</i><i style="--w:20%">问题与设计</i><i style="--w:18%">验证</i><i style="--w:14%">运行反馈</i></div></div><b class="shift-arrow">重心转移 →</b><div><span>AI 压缩实现后</span><div class="attention-bar new"><i style="--w:18%">实现</i><i style="--w:29%">问题与约束</i><i style="--w:28%">验证与审查</i><i style="--w:25%">运行反馈</i></div></div></div><p class="chart-caption">这是时间重心的概念示意，不是行业统计；变化的是比重，不是工程师突然多了新职责。</p>`),
  S('统一方法论', '实现变便宜了，这四件事依然昂贵', cards([
    ['架构判断','在多种可行方案中做取舍。'],
    ['责任','为最终产物与后果负责。'],
    ['验证','把“看起来对”变成证据。'],
    ['品味','知道什么值得留下。']
  ],4)),
  S('统一方法论', '把前面的做法，收成五组工程控制', `<div class="principle-controls"><div><span>01</span><b>记忆</b><p>上下文写进仓库<br>修正留给下一次</p></div><div><span>02</span><b>边界</b><p>先定义成功与非目标<br>以纵向切片推进</p></div><div><span>03</span><b>证据</b><p>先写验收条件<br>软件测试 · 硬件测量 · 写作来源</p></div><div><span>04</span><b>分工</b><p>研究、设计、实现、审查分开<br>AI 铺开，人把方向</p></div><div><span>05</span><b>约束</b><p>用确定性工具约束模型<br>让工程纪律被放大</p></div></div>`, {kicker:'FIVE ENGINEERING CONTROLS'}),
  S('统一方法论', 'AI 让构建、衡量、学习的每一轮更快', `<div class="d3-chart d3-flywheel" data-chart="flywheel" aria-label="AI 加速构建、衡量、学习飞轮，并串联软件、硬件和知识三个项目"></div>${evidence('持续优势','谁能用 AI 加快软件、硬件和知识生产的每一次循环，谁就能更快试错、更早学会，也更容易建立持续优势。')}`, {kicker:'BUILD · MEASURE · LEARN'}),

  // 67–81 话题四与结尾：AI 时代的软件开发与职业规划
  S('转场', '当飞轮越转越快，工程师还负责什么？', `<p class="lead">AI 可以加快每一轮构建、衡量和学习。接下来要问：当这种速度成为常态，团队怎么分工，个人又该把时间花在哪里？</p>${chip(['交付 → 方向','产出 → 结果','工具 → 能力'])}`, {type:'cover', transition:true, kicker:'FROM METHOD TO CAREER', visual:VISUALS.systemToCareer}),
  S('话题四 · 下一站：工程师的未来', '04<br><span class="accent">下一站：工程师的未来</span>', `<p class="lead">AI 改变的不只是编码速度，也会改变我们怎样衡量产出、怎样组织团队，以及工程师靠什么建立长期价值。</p>${chip(['SOFTWARE','TEAM','CAREER','RESPONSIBILITY'])}`, {type:'cover', kicker:'TOPIC 04 · THE ENGINEER', visual:VISUALS.futureEngineer}),
  S('话题四 · 下一站：工程师的未来', '软件产出，该怎么衡量？', `<div class="production-shift"><div><span>容易统计的产物</span><strong>代码、PR、文件</strong><p>它们能说明发生了工作，不能说明问题已经解决。</p></div><i>→</i><div class="active"><span>真正需要负责的结果</span><strong>经过验证的新能力</strong><p>从需求、实现、测试一直到运行证据。</p></div></div>${evidence('看结果','别数 Agent 生成了多少文件，要看系统最后多了什么：能不能验证、能不能维护、能不能长期运行。')}`, {kicker:'UNIT OF PRODUCTION'}),
  S('话题四 · 下一站：工程师的未来', '实现越快，工程师越要守住两端', `<div class="d3-chart d3-lifecycle" data-chart="lifecycle" aria-label="实现环节更容易自动化，人的判断与注意力更多分布在需求、验证和运行两端"></div><p class="chart-caption">概念示意：AI 优先压缩中间的实现成本，但不会自动替你定义问题、判断证据和接管失败。</p>`, {kicker:'A QUALITATIVE SHIFT'}),
  S('话题四 · 下一站：工程师的未来', '任务能交多远，要看两件事', `<div class="d3-chart d3-delegation" data-chart="delegationMap" aria-label="根据机器能否独立验证和失败影响决定任务可以授权给 Agent 到什么程度"></div><p class="chart-caption">验证越清楚、失败影响越可控，Agent 才能拿到更大的执行权限。</p>`, {kicker:'VERIFIABILITY × CONSEQUENCE'}),
  S('话题四 · 下一站：工程师的未来', '团队不会消失，协作方式会变', `<div class="d3-chart d3-team" data-chart="teamTopology" aria-label="负责人设定方向和权限，多个 Agent 并行协作，真实反馈回流并将异常升级给人"></div>${evidence('组织变化','更少的人可以负责更大的工程范围，但角色、权限、反馈和出问题后的接管路径必须先设计清楚。')}`, {kicker:'TEAM TOPOLOGY'}),
  S('话题四 · 下一站：工程师的未来', '实现可以委托，责任不会转移', `<div class="responsibility-map"><div class="delegation-core"><span>可以委托</span><b>实现</b><small>生成 · 修改 · 执行</small></div><div class="responsibility-boundary">人的责任边界</div><div class="responsibility-items"><div><span>01</span><b>解释</b><small>为什么这样设计</small></div><div><span>02</span><b>识别未知</b><small>模型不知道什么</small></div><div><span>03</span><b>接管失败</b><small>缩小并解决问题</small></div><div><span>04</span><b>承担后果</b><small>安全 · 成本 · 用户</small></div></div></div>`, {kicker:'RESPONSIBILITY BOUNDARY'}),
  S('话题四 · 下一站：工程师的未来', '未来工程师的四层能力', `<div class="moat-stack"><div style="--w:52%"><b>04 · 问题选择与工程品味</b><span>决定什么值得做</span></div><div style="--w:66%"><b>03 · 验证与责任</b><span>知道怎样证明正确</span></div><div style="--w:80%"><b>02 · 系统与领域</b><span>理解约束和长期结构</span></div><div style="--w:94%"><b>01 · 工具与实现</b><span>熟练调用模型和自动化</span></div></div><p class="muted" style="margin-top:24px">工具最容易学会，也最容易被复制；越往上，越需要长期实践。</p>`, {kicker:'LONG-TERM CAPABILITIES'}),
  S('话题四 · 下一站：工程师的未来', '个人贡献者和管理者，各自要补什么？', `<div class="career-paths"><div><span class="eyebrow">个人贡献者</span><h3>成为系统型工程师</h3>${list(['扎进一个真实领域','设计可执行的项目上下文','建立可靠的验证工具','对跨组件结果负责'])}</div><div><span class="eyebrow">工程管理者</span><h3>重新设计团队协作</h3>${list(['划分人和 Agent 的权限','设计任务与接管路径','管理质量、成本和风险','把团队经验写进系统'])}</div></div>`, {kicker:'TWO PATHS'}),
  S('话题四 · 下一站：工程师的未来', '接下来一年，可以从哪里开始？', `<div class="action-roadmap"><section><header><span>0—30 天</span><b>跑通一个闭环</b></header><ol><li>选每周都会重复、失败可以复现的真实任务</li><li>记录当前耗时、返工次数和常见失败</li><li>写入项目上下文，并补一条自动验收</li></ol><footer><span>交付物</span><strong>可重复执行的任务闭环</strong></footer></section><section><header><span>31—90 天</span><b>交付一个纵向切片</b></header><ol><li>让 Agent 贯穿研究、规格、实现、测试和审查</li><li>把至少十次有效修正写成测试、规格或规则</li><li>比较周期、缺陷和人工接管点的变化</li></ol><footer><span>交付物</span><strong>真实用户正在使用的端到端能力</strong></footer></section><section><header><span>91—365 天</span><b>建立领域系统</b></header><ol><li>积累可复用的规格、评估集和工作方法</li><li>设计权限、审查与异常接管路径</li><li>对质量、成本、运行结果和用户后果负责</li></ol><footer><span>交付物</span><strong>能持续运行、持续验证的工程系统</strong></footer></section></div>`, {kicker:'ACTION PLAN'}),
  S('话题四 · 下一站：工程师的未来', '答案越来越便宜，问题反而更重要', `${quotation('工具能替我们回答问题，却不能替我们决定：<em>什么值得追问，什么值得做成现实。</em>','好奇心让我们继续追问；想象力让我们看见还不存在的可能。')}`, {kicker:'CURIOSITY'}),
  S('话题四 · 下一站：工程师的未来', '想象力，也是一种工程能力', `<div class="d3-chart d3-imagination" data-chart="imaginationLoop" aria-label="从一个真实问题发散出多个可能，收敛为可检验假设，经过实验后由现实修正方向"></div>${evidence('缺一不可','没有想象力，AI 只会更快地重复昨天；没有验证，想象力也只能停在故事里。')}`, {kicker:'DIVERGE → TEST → LEARN'}),
  S('话题四 · 下一站：工程师的未来', '不要和 AI 比谁写得更快', `<div class="manifesto-quote"><span class="quote-mark">“</span><p>去成为那个<br><em>定义方向</em>、<em>设计系统</em>、<em>建立证据</em><br>并对结果负责的人。</p><div class="manifesto-rule"></div><footer><span>方向</span><span>系统</span><span>证据</span><span>责任</span></footer></div>`, {type:'manifesto', kicker:'TOPIC 04 · CONCLUSION'}),
  S('结束', '如果效率不再稀缺，我们想放大什么？', `<div class="future-questions future-questions-final"><p>我们会做出更多真正有用的东西，还是更多没人需要的功能？</p><p>当一个人可以调度一支 Agent 团队，哪些判断仍然不该交给模型？</p><p>当代码随时可以重写，什么仍然值得我们长期维护？</p><p>十年后回头看，我们希望 AI 放大的只是效率，<br>还是人的好奇心、想象力与责任感？</p></div>`, {kicker:'QUESTIONS FOR THE FUTURE'}),
  S('结束', '速度已经到来，方向仍由我们选择', `<div class="d3-chart d3-final" data-chart="futureCompass" aria-label="AI 加速软件、硬件和知识生产，人围绕方向、证据、想象力与责任做出选择"></div>`, {kicker:'谢谢 · Q&A'})
];

window.SLIDE_CONTENT = slides.filter(slide => !slide.hidden);
